#!/usr/bin/env bash

# Summary: Open the GitHub page for a repository
#
# Usage: {cmd} [project]
# Options:
#   project (`dev pj list`): The project to open
#
# If no project is given, use the current github repository

set -e

# TODO: extract the code to cd into existing project

declare -A args="($_DEV_ARGS)"

project="${args[project]}"

# Change into project directory
if [ -n "$project" ]; then
    cd "$WORKSPACE/$project"
fi

# Open the GitHub page
gh repo view --web
