name: 'Failure Report'
description: 'Reports a test failure by creating or updating an issue assigned to a specified user'
inputs:
  assignee:
    description: 'GitHub username to assign the issue to'
    required: true
outputs:
  issue-number:
    description: 'The number of the issue used for tracking'
runs:
  using: 'node20'
  main: 'index.js'
