add_newline = true

[character]
success_symbol = "[✓](bold green) [»](cyan)"
error_symbol = "[✗](bold red) [»](cyan)"

[directory.substitutions]
"Documents" = "📄"
"Downloads" = "⬇️"
"Music" = "🎵"
"Pictures" = "📷"
"workspace" = "⚙️"
