# TODO: extract this to a macOS-specific thing
alias ls='ls -G'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias d='docker'
alias e='emacs'
alias g='git'
alias l='ls -CFh'
alias la='ls -CFAh'
alias ll='ls -CFAlh'
alias r='rails'
alias rs='rspec'
alias t='tmux'
