name: 'Report failed scenario'
description: |
  Reports a that a test scenario has failed by creating or updating issues.

  For each user or group, we'll maintain a single tracking issue,
  where failed scenarios are reported as comments.
inputs:
  owners:
    description: 'Comma-separated list of GitHub usernames or groups reponsible for the scenario'
    required: true
  scenario:
    description: 'Name of the scenario that failed'
    required: true
  test-output:
    description: 'Standard output of the failed test'
    required: true
  
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const dependencies = { context, core, github };
          const owners = "${{ inputs.owners }}".split(',');
          const scenario = "${{ inputs.scenario }}";
          const testOutput = "${{ inputs.test-output }}";

          return require('${{ github.action_path }}/report-failure.js')(dependencies, owners, scenario, testOutput);
