#!/usr/bin/env bash
#
# Summary: Opens a project for development
#
# Usage: {cmd} <project>
#
# Changes into the project directory and opens a zellij session 
# named after that project
#
# If a .config/zellij.kdl file exists in the project, it will be used to
# create the zellij session, otherwise a default session is created with an
# editor and a terminal window (the 'dev-utils' layout).

set -e

# Provide completions
if [ "$1" = "--complete" ]; then
  dev pj list
  exit 0
fi

project="$1"

# Extract last component for the name
name="${project##*/}"

# Remove characters that can't appear in the zellij session name
name="${name//./-}"

# Truncate the name to avoid zellij hanging
# See: https://github.com/zellij-org/zellij/issues/2591
name="$(echo $name | head -c35)~"

# Change into project directory
cd "$WORKSPACE/$project"

# Determine the approprate layout
layout="$WORKSPACE/$project/.config/zellij.kdl"
if ! [ -f "$layout" ]; then
  layout="dev-utils"
fi

# Create or attach to zellij session
zellij --session "$name" --layout "$layout" \
  || zellij attach "$name"

