#!/usr/bin/env bash
#
# Summary: Add coauthors to the git HEAD
#
# Usage: {cmd} [coauthor]...
# Options:
#   coauthor (`cat "$HOME/.config/git/coauthors.json" | jq -r 'keys.[]'`): Short names of coauthors, looked up in $HOME/.config/git/coauthors.json

set -e

formatCoauthor() {
    jq -r '"--trailer=Co-authored-by: " + .name + " <" + .email + ">"'
}

declare -A args="($_DEV_ARGS)"
config=$(cat "$HOME/.config/git/coauthors.json")

trailers=()
for coauthor in ${args[coauthor]}; do
    entry="$(echo "$config" | jq ".[\"$coauthor\"]")"

    if [ "$entry" = "null" ]; then
        echo "Coauthor '$coauthor' not found."
        exit 1
    fi

    trailers+=("$(echo "$entry" | formatCoauthor)")
done

git commit --amend "${trailers[@]}"
