#!/usr/bin/env bash
#
# Summary: Reset current git repository for development.
#
# Usage: {cmd}

set -e

# Include utilities to interactive with the user
# shellcheck disable=SC1091 # _DEV_ROOT will be set appropriately
source "${_DEV_ROOT}/lib/interactive.sh"

# Make sure we are up to date with origin
git fetch --prune --tags

# Figure out the name of the main branch
if git rev-parse --verify "origin/main" &>/dev/null; then
  BRANCH="main"
elif git rev-parse --verify "origin/published" &>/dev/null; then
  BRANCH="published"
else
  BRANCH="master"
fi

# Remove untracked files, but confirm first
changed_files="$(git clean -fdn | sed 's/^Would remove /  /')"
if [ -n "$changed_files" ]; then
  echo "Following files will be removed:"
  echo "$changed_files"

  if ask_yes_or_no "Are you sure they should be removed?" N; then
    git clean -fd
  else
    exit 1
  fi
fi

git checkout "$BRANCH"
git clean-branches
git pull --rebase
