name: Test Workflow

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Output placeholder message
        run: echo "This is a placeholder workflow that will be developed in another branch"