name: Test Workflow

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        id: create-issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Test issue",
              body: "test issue body",
              assignees: ["ggazzi"]  // Hardcoded username
            });
            console.log(`Created issue #${response.data.number}: ${response.data.html_url}`);
            return response.data;