name: Test Workflow

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Report test failure
        id: report-failure
        uses: ./.github/actions/report-failure
        with:
          owners: "ggazzi"
          scenario: "foo"
          test-output: "logslogslogslogs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
