name: Test Workflow

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        id: create-issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignee = "ggazzi";

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignee,
              labels: "failure-tracker",
            });

            let trackingIssue;
            if (issues.data.length === 1) {
              trackingIssue = issues.data[0];
              console.log(`Found tracking issue #${trackingIssue.number}: ${trackingIssue.title}`);
            
            } else if (issues.data.length === 0) {
              const newIssue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Failure Tracker for ${assignee}`,
                body: 'This issue tracks test failures that need attention.',
                assignee,
                labels: ['failure-tracker', 'bug']
              });
              trackingIssue = newIssue.data;
              console.log(`Created tracking issue #${trackingIssue.number}`);
            
            } else {
              console.error(`Found ${issues.data.length} failure tracker issues for ${assignee}, expected at most one.`);
              for (const issue of issues.data) {
              console.error(`Issue #${issue.number}: ${issue.title}`);
              }
              process.exit(1);
            }

            const now = new Date().toISOString();
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: trackingIssue.number,
              body: `@${assignee}: Test failure detected at ${now} in [workflow run](${runUrl}).`
            });

            if (trackingIssue.state === 'closed') {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: trackingIssue.number,
                state: 'open'
              });
            }
                      
            console.log(`Added failure report to issue #${trackingIssue.number}`);
